[package]
name = "blight"
description = "A hassle-free CLI utility to manage backlight on Linux laptops with hybrid GPU configuration."
categories = ["command-line-utilities"]
keywords = ["backlight","CLI","utility","hybrid-gpu","brightness"]
authors = ["Maaz Ahmed <mzahmed95@gmail.com>"]
repository = "https://github.com/VoltaireNoir/blight"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
futures = "0.3.21"

[profile.release]
strip = true
lto = true
panic = 'abort'
